name: env check action
description: 'Hello'
runs:
  using: composite
  steps:
    - name: show envs in action
      run: env | sort
      shell: bash
    - name: show $GITHUB_ENV
      run: cat $GITHUB_ENV
      shell: bash