name: reusable-wf-test

on:
  workflow_dispatch:
  push:

env:
  MY_WORKFLOW_ENV: MY_WORKFLOW_ENV_VALUE
jobs:
  call-reusable-wf:
    uses: kazuo278/env-check-action/.github/workflows/reusable-wf.yaml@main
