name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: envs in action via file path
        uses: ./.
      - name: envs in action via repo path of main branch
        uses: kazuo278/env-check-action@main
      - name: envs in action via repo path of feature/test branch
        uses: kazuo278/env-check-action@feature/test
      - name: envs in action via repo path of tags
        uses: kazuo278/env-check-action@v1
      - name: envs in worlflow
        run: env | sort
      - name: step summary
        run: cat $GITHUB_STEP_SUMMARY
      - name: state
        run: cat $GITHUB_STATE
